### ISSUE TITLE
Support multiple parallel streams

### ISSUE THREAD

**Issue by jscheid** [aolsenjazz/libsamplerate-js#10]
As requested in #8: let's say you're downloading an audio file in [chunks](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) and you want to resample it. For best results you'd want to feed the chunks to libsamplerate as they arrive, this way doing Network I/O and processing in parallel.

With the current version of this lib you'll have to make sure that you only process a single audio file in this way; if you wanted to download and resample multiple files chunk-wise in parallel, you'd need more than one `SRC_STATE` because due to the async nature of JavaScript, chunks from different files are likely to arrive interleaved in the same thread.

**Comment by aolsenjazz** [comment]
Cool. Will need to do some reading on the streams API first. Will circle back with a proposed API for your use case.

**Comment by jscheid** [comment]
The stream API was really just an example, I don't think you need to dive into it. The bottom line is just that ideally there was a way to have multiple `SRC_STATE`s, so you can process multiple files in parallel.

**Comment by aolsenjazz** [comment]
While I still see the value in this, I’d prefer to leave the API identical to SRC. Closing unless lots of demand for this feature pops up in future.
