### ISSUE TITLE
Add support for node

### ISSUE THREAD

**Issue by Sshhcc** [aolsenjazz/libsamplerate-js#2]
![image](https://user-images.githubusercontent.com/17444344/118576972-23f62280-b7bc-11eb-8b77-0f108a89aa47.png)
how can i solve it

**Comment by aolsenjazz** [comment]
Judging by the line from the stack trace `at Object.<anonymous> (/Users/sun/project/html/js/voiceTalk/server.js:3:23)` it seems that you're trying to use this library outside of a browser environment - is this correct? This library is designed to be used in-browser.

I can look into make this available in node as well. Please confirm.

**Comment by Sshhcc** [comment]
yes,i used it on node,it can only work on browser?

**Comment by aolsenjazz** [comment]
That is correct. Will mark this as feature request and notify as it changes in the future.

**Comment by Sshhcc** [comment]
ok。thanks

**Comment by aolsenjazz** [comment]
Added support for node. Tested using node 12.18, but should be compatible with older version of node.

Also added an examples showing usage in node in the _examples_ directory. Nothing is really different.

Please do try it out and let me know if there are any hiccups!
